ALTER TABLE public.schema_migration ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.geo_unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_dataset ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metric_definition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.derived_observation ENABLE ROW LEVEL SECURITY;