"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const locales = ["de", "en", "fr", "it"] as const;
export type Locale = (typeof locales)[number];

const messages = {
  de: {
    siteName: "Politik Kompass Schweiz", language: "Sprache", map: "Karte", sources: "Quellen", methodology: "Berechnung", cesMethodology: "Was ist der Cultural Enrichment Score?", backToCantonMap: "Kantonskarte", municipalVoteResults: "Gemeinde-Abstimmungsresultate", mainFooter: "BFS · SEM · Lokaler Datenkatalog", nudge: "Klick auf einen Kanton – los geht's!",
    mapLoading: "Kantonskarte wird geladen …", mapFailed: "Die Kantonskarte konnte nicht geladen werden.", mapNoValues: "Keine Kantonswerte", cantonAction: "Kantonsdaten anzeigen", cantonMapAria: "Interaktive Karte der Schweizer Kantone", mapReset: "Kartenansicht zurücksetzen",
    mapCatalogFailed: "Der lokale Datenkatalog konnte nicht geladen werden.", mapValuesFailed: "Die Kartenwerte konnten nicht geladen werden.", cantonDataFailed: "Die Kantonsdaten konnten nicht geladen werden.", sourcesFailed: "Die Quellen konnten nicht geladen werden.", loading: "Wird geladen …", unavailable: "Nicht verfügbar", notImported: "Nicht importiert",
    municipalityLevel: "Gemeinde-Ebene", politicalCompass: "Politischer Kompass", closeCanton: "Fixierte Kantonsdaten schliessen", population: "Einwohnerzahl", crime: "Kriminalität (PKS)", asylum: "Offene Asylverfahren", foreignPopulation: "Ausländische Bevölkerung", fertility: "Fertilitätsrate", unemployment: "Erwerbslosenquote (BFS)", politicalTendency: "Politische Tendenz", culturalScore: "Cultural Enrichment Score", tendencyBalanced: "ausgeglichen", tendencyLightLeft: "leicht links", tendencyLeft: "links", tendencyLightRight: "leicht rechts", tendencyRight: "rechts",
    sourcesKicker: "DATENGRUNDLAGEN", sourcesTitle: "Quellen", closeSources: "Quellen schliessen", sourcesLoading: "Quellen werden geladen …", openSource: "Originalquelle öffnen", localCalculation: "Lokale Berechnung aus den genannten Datenquellen", asOf: "Stand {date}",
    cesTitle: "Cultural Enrichment Score", closeMethodology: "Berechnung schliessen", cesText: "Nicht amtlicher Kompositindex. Alle vier Faktoren werden über die aktuell verfügbaren Kantone auf 0 bis 100 normiert und zählen gleich stark.", cesFormula: "CES = 0.25 × (Kriminalität + offene Asylverfahren + ausländische Bevölkerung + Erwerbslosenquote)", cesCrime: "Kriminalität pro 100'000: 2025", cesAsylum: "Offene Asylverfahren pro 1'000: 30.06.2026", cesForeign: "Ausländische Bevölkerung: 2024", cesUnemployment: "BFS-Erwerbslosenquote: 2024", cesMissing: "Für Appenzell Innerrhoden ist kein Score verfügbar, da keine Erwerbslosenquote veröffentlicht wurde.",
    municipalityLoading: "Gemeinde-Abstimmungen werden geladen …", municipalityFailed: "Die BFS-Abstimmungsdaten konnten nicht geladen werden.", municipalitiesIn: "Gemeinden in {canton}", municipalityMapAria: "Gemeinden in {canton}, eingefärbt nach ihrer Position im politischen Kompass", municipalityResultsAria: "Abstimmungsresultate für {municipality}", closeMunicipality: "Fixierte Gemeindedaten schliessen", eligibleVoters: "Stimmberechtigte", noCompassPosition: "Keine Kompassposition verfügbar.", municipalityPosition: "Position von {municipality} im politischen Kompass", yes: "Ja", no: "Nein", turnout: "Beteiligung", provisional: "provisorisch", municipalSource: "Quelle: Bundesamt für Statistik (BFS), eidgenössische Abstimmungsresultate auf Gemeindeebene. Die Karte enthält die 2'105 räumlichen Gemeinden; 12 Auslandsgemeinden ohne Fläche sind nicht kartiert.",
    compassCantons: "Politischer Kompass der Kantone", compassMunicipalities: "Politischer Kompass der Gemeinden", compassClose: "Politischen Kompass schliessen", cantons: "Kantone", all: "Alle", none: "Keine", searchMunicipality: "Gemeinde suchen …", clearSearch: "Gemeindesuche zurücksetzen", searchResults: "Passende Gemeinden", compassCalculationAria: "Berechnung des politischen Kompasses", compassMethodOne: "Für jede Vorlage wird der exakte Ja-Anteil einer Gemeinde mit dem offiziellen Schweizer Ja-Anteil verglichen. Die Differenz wird durch die Streuung aller Gemeindeanteile geteilt und auf ±3 Standardabweichungen begrenzt.", compassMethodTwo: "Diese standardisierten Differenzen werden mit den Gewichten unten zu X (wirtschaftlich links ↔ rechts) und Y (libertär ↔ autoritär) summiert. Für die Darstellung wird jede Achse so gedehnt, dass die äussersten Punkte den Rand erreichen; die Reihenfolge der Positionen bleibt dabei erhalten. Das sind relative Modellpositionen, keine objektiven Tatsachen über Menschen oder Orte.", proposal: "Vorlage", economy: "Wirtschaft", authority: "Autorität", excluded: "Ausgeschlossen", compassMissing: "Für die geöffnete aktuelle Gemeinde liegen nicht alle neun zuordenbaren Resultate vor. Sie erhält deshalb keinen erfundenen Punkt; der Kompass zeigt weiterhin alle verfügbaren Gemeinden.", compassLoading: "Kompassdaten werden geladen …", compassFailed: "Der politische Kompass konnte nicht geladen werden.", authoritarian: "Autoritär", libertarian: "Libertär", left: "Links", right: "Rechts", resetCompass: "Kompassansicht zurücksetzen", resetView: "Ansicht zurücksetzen", compassFooter: "Quelle: BFS voteinfo, eidgenössische Abstimmungen auf Gemeindeebene.", allMunicipalitiesMapped: "Alle aktuellen räumlichen BFS-Gemeinden sind zugeordnet.", missingMunicipalities: "{count} aktuelle Gemeinden ohne vollständige Zuordnung sind nicht positioniert.",
  },
  en: {
    siteName: "Swiss Political Compass", language: "Language", map: "Map", sources: "Sources", methodology: "Method", cesMethodology: "What is the Cultural Enrichment Score?", backToCantonMap: "Canton map", municipalVoteResults: "Municipal voting results", mainFooter: "FSO · SEM · Local data catalogue", nudge: "Click a canton — let's go!",
    mapLoading: "Loading canton map …", mapFailed: "The canton map could not be loaded.", mapNoValues: "No canton values", cantonAction: "Show canton data", cantonMapAria: "Interactive map of the Swiss cantons", mapReset: "Reset map view",
    mapCatalogFailed: "The local data catalogue could not be loaded.", mapValuesFailed: "The map values could not be loaded.", cantonDataFailed: "The canton data could not be loaded.", sourcesFailed: "The sources could not be loaded.", loading: "Loading …", unavailable: "Not available", notImported: "Not imported",
    municipalityLevel: "Municipality level", politicalCompass: "Political Compass", closeCanton: "Close pinned canton data", population: "Population", crime: "Crime (PCS)", asylum: "Pending asylum cases", foreignPopulation: "Foreign population", fertility: "Fertility rate", unemployment: "Unemployment rate (FSO)", politicalTendency: "Political tendency", culturalScore: "Cultural Enrichment Score", tendencyBalanced: "balanced", tendencyLightLeft: "slightly left", tendencyLeft: "left", tendencyLightRight: "slightly right", tendencyRight: "right",
    sourcesKicker: "DATA SOURCES", sourcesTitle: "Sources", closeSources: "Close sources", sourcesLoading: "Loading sources …", openSource: "Open original source", localCalculation: "Local calculation from the stated data sources", asOf: "As of {date}",
    cesTitle: "Cultural Enrichment Score", closeMethodology: "Close methodology", cesText: "Unofficial composite index. The four factors are normalized from 0 to 100 across all currently available cantons and carry equal weight.", cesFormula: "CES = 0.25 × (crime + pending asylum cases + foreign population + unemployment rate)", cesCrime: "Crime per 100,000: 2025", cesAsylum: "Pending asylum cases per 1,000: 30 Jun 2026", cesForeign: "Foreign population: 2024", cesUnemployment: "FSO unemployment rate: 2024", cesMissing: "No score is available for Appenzell Innerrhoden because no unemployment rate was published.",
    municipalityLoading: "Loading municipal voting results …", municipalityFailed: "The FSO voting data could not be loaded.", municipalitiesIn: "Municipalities in {canton}", municipalityMapAria: "Municipalities in {canton}, coloured by their political compass position", municipalityResultsAria: "Voting results for {municipality}", closeMunicipality: "Close pinned municipality data", eligibleVoters: "Eligible voters", noCompassPosition: "No compass position available.", municipalityPosition: "Position of {municipality} on the political compass", yes: "Yes", no: "No", turnout: "Turnout", provisional: "provisional", municipalSource: "Source: Federal Statistical Office (FSO), federal voting results at municipal level. The map contains 2,105 spatial municipalities; 12 foreign municipalities without an area are not mapped.",
    compassCantons: "Political Compass of the Cantons", compassMunicipalities: "Political Compass of the Municipalities", compassClose: "Close political compass", cantons: "Cantons", all: "All", none: "None", searchMunicipality: "Search municipality …", clearSearch: "Clear municipality search", searchResults: "Matching municipalities", compassCalculationAria: "Political compass calculation", compassMethodOne: "For each proposal, a municipality's exact yes share is compared with the official Swiss yes share. The difference is divided by the spread of all municipal shares and capped at ±3 standard deviations.", compassMethodTwo: "These standardized differences are weighted below and summed into X (economic left ↔ right) and Y (libertarian ↔ authoritarian). For display, each axis is stretched so the outermost points reach the edge; the order of positions is preserved. These are relative model positions, not objective facts about people or places.", proposal: "Proposal", economy: "Economy", authority: "Authority", excluded: "Excluded", compassMissing: "The currently opened municipality does not have all nine matching results. No point is invented for it; the compass continues to show every available municipality.", compassLoading: "Loading compass data …", compassFailed: "The political compass could not be loaded.", authoritarian: "Authoritarian", libertarian: "Libertarian", left: "Left", right: "Right", resetCompass: "Reset compass view", resetView: "Reset view", compassFooter: "Source: FSO voteinfo, federal votes at municipal level.", allMunicipalitiesMapped: "All current spatial FSO municipalities are matched.", missingMunicipalities: "{count} current municipalities without complete matching are not positioned.",
  },
  fr: {
    siteName: "Boussole politique suisse", language: "Langue", map: "Carte", sources: "Sources", methodology: "Méthode", cesMethodology: "Qu'est-ce que le Cultural Enrichment Score ?", backToCantonMap: "Carte des cantons", municipalVoteResults: "Résultats des votations communales", mainFooter: "OFS · SEM · Catalogue de données local", nudge: "Cliquez sur un canton — c'est parti !",
    mapLoading: "Chargement de la carte des cantons …", mapFailed: "La carte des cantons n'a pas pu être chargée.", mapNoValues: "Aucune valeur cantonale", cantonAction: "Afficher les données cantonales", cantonMapAria: "Carte interactive des cantons suisses", mapReset: "Réinitialiser la carte",
    mapCatalogFailed: "Le catalogue de données local n'a pas pu être chargé.", mapValuesFailed: "Les valeurs de la carte n'ont pas pu être chargées.", cantonDataFailed: "Les données cantonales n'ont pas pu être chargées.", sourcesFailed: "Les sources n'ont pas pu être chargées.", loading: "Chargement …", unavailable: "Non disponible", notImported: "Non importé",
    municipalityLevel: "Niveau communal", politicalCompass: "Boussole politique", closeCanton: "Fermer les données cantonales épinglées", population: "Population", crime: "Criminalité (SPC)", asylum: "Demandes d'asile en cours", foreignPopulation: "Population étrangère", fertility: "Taux de fécondité", unemployment: "Taux de chômage (OFS)", politicalTendency: "Tendance politique", culturalScore: "Cultural Enrichment Score", tendencyBalanced: "équilibré", tendencyLightLeft: "légèrement à gauche", tendencyLeft: "à gauche", tendencyLightRight: "légèrement à droite", tendencyRight: "à droite",
    sourcesKicker: "SOURCES DE DONNÉES", sourcesTitle: "Sources", closeSources: "Fermer les sources", sourcesLoading: "Chargement des sources …", openSource: "Ouvrir la source originale", localCalculation: "Calcul local à partir des sources indiquées", asOf: "État : {date}",
    cesTitle: "Cultural Enrichment Score", closeMethodology: "Fermer la méthode", cesText: "Indice composite non officiel. Les quatre facteurs sont normalisés de 0 à 100 parmi les cantons actuellement disponibles et ont le même poids.", cesFormula: "CES = 0.25 × (criminalité + demandes d'asile en cours + population étrangère + chômage)", cesCrime: "Criminalité pour 100'000 : 2025", cesAsylum: "Demandes d'asile en cours pour 1'000 : 30.06.2026", cesForeign: "Population étrangère : 2024", cesUnemployment: "Taux de chômage OFS : 2024", cesMissing: "Aucun score n'est disponible pour Appenzell Rhodes-Intérieures, car aucun taux de chômage n'a été publié.",
    municipalityLoading: "Chargement des résultats communaux …", municipalityFailed: "Les données de votation de l'OFS n'ont pas pu être chargées.", municipalitiesIn: "Communes de {canton}", municipalityMapAria: "Communes de {canton}, colorées selon leur position dans la boussole politique", municipalityResultsAria: "Résultats de votation pour {municipality}", closeMunicipality: "Fermer les données communales épinglées", eligibleVoters: "Électeurs inscrits", noCompassPosition: "Aucune position disponible.", municipalityPosition: "Position de {municipality} dans la boussole politique", yes: "Oui", no: "Non", turnout: "Participation", provisional: "provisoire", municipalSource: "Source : Office fédéral de la statistique (OFS), résultats des votations fédérales au niveau communal. La carte contient 2'105 communes spatiales ; 12 communes à l'étranger sans surface ne sont pas cartographiées.",
    compassCantons: "Boussole politique des cantons", compassMunicipalities: "Boussole politique des communes", compassClose: "Fermer la boussole politique", cantons: "Cantons", all: "Tous", none: "Aucun", searchMunicipality: "Rechercher une commune …", clearSearch: "Effacer la recherche", searchResults: "Communes correspondantes", compassCalculationAria: "Calcul de la boussole politique", compassMethodOne: "Pour chaque objet, la part exacte de oui d'une commune est comparée à la part officielle de oui suisse. La différence est divisée par la dispersion de toutes les parts communales et limitée à ±3 écarts-types.", compassMethodTwo: "Ces différences standardisées sont pondérées ci-dessous et additionnées en X (gauche ↔ droite économique) et Y (libertaire ↔ autoritaire). Pour l'affichage, chaque axe est étiré afin que les points les plus éloignés atteignent le bord ; l'ordre des positions est conservé. Il s'agit de positions relatives de modèle, pas de faits objectifs sur des personnes ou des lieux.", proposal: "Objet", economy: "Économie", authority: "Autorité", excluded: "Exclus", compassMissing: "La commune ouverte ne dispose pas des neuf résultats correspondants. Aucun point n'est inventé ; la boussole affiche toujours toutes les communes disponibles.", compassLoading: "Chargement des données de la boussole …", compassFailed: "La boussole politique n'a pas pu être chargée.", authoritarian: "Autoritaire", libertarian: "Libertaire", left: "Gauche", right: "Droite", resetCompass: "Réinitialiser la boussole", resetView: "Réinitialiser la vue", compassFooter: "Source : OFS voteinfo, votations fédérales au niveau communal.", allMunicipalitiesMapped: "Toutes les communes spatiales actuelles de l'OFS sont attribuées.", missingMunicipalities: "{count} communes actuelles sans attribution complète ne sont pas positionnées.",
  },
  it: {
    siteName: "Bussola politica svizzera", language: "Lingua", map: "Mappa", sources: "Fonti", methodology: "Metodo", cesMethodology: "Cos'è il Cultural Enrichment Score?", backToCantonMap: "Mappa dei cantoni", municipalVoteResults: "Risultati delle votazioni comunali", mainFooter: "UST · SEM · Catalogo dati locale", nudge: "Clicca su un cantone — si parte!",
    mapLoading: "Caricamento della mappa dei cantoni …", mapFailed: "Impossibile caricare la mappa dei cantoni.", mapNoValues: "Nessun valore cantonale", cantonAction: "Mostra i dati cantonali", cantonMapAria: "Mappa interattiva dei cantoni svizzeri", mapReset: "Reimposta la mappa",
    mapCatalogFailed: "Impossibile caricare il catalogo dati locale.", mapValuesFailed: "Impossibile caricare i valori della mappa.", cantonDataFailed: "Impossibile caricare i dati cantonali.", sourcesFailed: "Impossibile caricare le fonti.", loading: "Caricamento …", unavailable: "Non disponibile", notImported: "Non importato",
    municipalityLevel: "Livello comunale", politicalCompass: "Bussola politica", closeCanton: "Chiudi i dati cantonali fissati", population: "Popolazione", crime: "Criminalità (SCP)", asylum: "Procedure d'asilo pendenti", foreignPopulation: "Popolazione straniera", fertility: "Tasso di fecondità", unemployment: "Tasso di disoccupazione (UST)", politicalTendency: "Tendenza politica", culturalScore: "Cultural Enrichment Score", tendencyBalanced: "equilibrato", tendencyLightLeft: "leggermente a sinistra", tendencyLeft: "a sinistra", tendencyLightRight: "leggermente a destra", tendencyRight: "a destra",
    sourcesKicker: "BASI DI DATI", sourcesTitle: "Fonti", closeSources: "Chiudi le fonti", sourcesLoading: "Caricamento delle fonti …", openSource: "Apri la fonte originale", localCalculation: "Calcolo locale dalle fonti indicate", asOf: "Stato: {date}",
    cesTitle: "Cultural Enrichment Score", closeMethodology: "Chiudi il metodo", cesText: "Indice composito non ufficiale. I quattro fattori sono normalizzati da 0 a 100 tra i cantoni attualmente disponibili e hanno lo stesso peso.", cesFormula: "CES = 0.25 × (criminalità + procedure d'asilo pendenti + popolazione straniera + disoccupazione)", cesCrime: "Criminalità per 100'000: 2025", cesAsylum: "Procedure d'asilo pendenti per 1'000: 30.06.2026", cesForeign: "Popolazione straniera: 2024", cesUnemployment: "Tasso di disoccupazione UST: 2024", cesMissing: "Non è disponibile alcun punteggio per Appenzello Interno, poiché non è stato pubblicato alcun tasso di disoccupazione.",
    municipalityLoading: "Caricamento dei risultati comunali …", municipalityFailed: "Impossibile caricare i dati di votazione UST.", municipalitiesIn: "Comuni in {canton}", municipalityMapAria: "Comuni in {canton}, colorati in base alla loro posizione nella bussola politica", municipalityResultsAria: "Risultati di votazione per {municipality}", closeMunicipality: "Chiudi i dati comunali fissati", eligibleVoters: "Aventi diritto di voto", noCompassPosition: "Nessuna posizione disponibile.", municipalityPosition: "Posizione di {municipality} nella bussola politica", yes: "Sì", no: "No", turnout: "Partecipazione", provisional: "provvisorio", municipalSource: "Fonte: Ufficio federale di statistica (UST), risultati delle votazioni federali a livello comunale. La mappa contiene 2'105 comuni spaziali; 12 comuni esteri senza superficie non sono rappresentati.",
    compassCantons: "Bussola politica dei cantoni", compassMunicipalities: "Bussola politica dei comuni", compassClose: "Chiudi la bussola politica", cantons: "Cantoni", all: "Tutti", none: "Nessuno", searchMunicipality: "Cerca un comune …", clearSearch: "Cancella la ricerca", searchResults: "Comuni corrispondenti", compassCalculationAria: "Calcolo della bussola politica", compassMethodOne: "Per ogni oggetto, la quota esatta di sì di un comune viene confrontata con la quota ufficiale svizzera. La differenza viene divisa per la dispersione di tutte le quote comunali e limitata a ±3 deviazioni standard.", compassMethodTwo: "Queste differenze standardizzate sono ponderate qui sotto e sommate in X (sinistra ↔ destra economica) e Y (libertario ↔ autoritario). Per la visualizzazione, ogni asse viene esteso affinché i punti più esterni raggiungano il bordo; l'ordine delle posizioni viene mantenuto. Sono posizioni relative di un modello, non fatti oggettivi su persone o luoghi.", proposal: "Oggetto", economy: "Economia", authority: "Autorità", excluded: "Esclusi", compassMissing: "Il comune aperto non dispone di tutti e nove i risultati corrispondenti. Non viene inventato alcun punto; la bussola continua a mostrare tutti i comuni disponibili.", compassLoading: "Caricamento dei dati della bussola …", compassFailed: "Impossibile caricare la bussola politica.", authoritarian: "Autoritario", libertarian: "Libertario", left: "Sinistra", right: "Destra", resetCompass: "Reimposta la bussola", resetView: "Reimposta vista", compassFooter: "Fonte: UST voteinfo, votazioni federali a livello comunale.", allMunicipalitiesMapped: "Tutti gli attuali comuni spaziali UST sono associati.", missingMunicipalities: "{count} comuni attuali senza associazione completa non sono posizionati.",
  },
} as const;

export type TranslationKey = keyof typeof messages.de;

type TranslationContextValue = { language: Locale; setLanguage: (language: Locale) => void; t: (key: TranslationKey, values?: Record<string, string | number>) => string };
const TranslationContext = createContext<TranslationContextValue | undefined>(undefined);

function interpolate(message: string, values: Record<string, string | number> = {}) {
  return message.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Locale>("de");

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem("politik-kompass-language", language);
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey, values?: Record<string, string | number>) => interpolate(messages[language][key], values) }), [language]);
  return <TranslationContext.Provider value={value}>{children}</TranslationContext.Provider>;
}

export function useTranslation() {
  const value = useContext(TranslationContext);
  if (!value) throw new Error("useTranslation must be used within LanguageProvider");
  return value;
}
